version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'his-webserver'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT}:/var/www:delegated
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled:delegated
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2:delegated
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini:delegated
  mysql:
    build: ./bin/mysql
    container_name: 'his-mysql'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql:delegated
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'his-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT:  ${PHPMYADMIN_UPLOAD_LIMIT}
    ports:
      - '8080:80'
    volumes: 
      - /sessions
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
  redis:
    container_name: 'his-sc-redis'
    image: redis:latest
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"